# Analysis options for Flutter project
include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
    - "**/generated_plugin_registrant.dart"
    - "build/**"
    - ".dart_tool/**"
  
  errors:
    # Disable problematic lints for production code
    avoid_print: ignore
    use_build_context_synchronously: ignore
    prefer_typing_uninitialized_variables: ignore
    strict_top_level_inference: ignore
    no_leading_underscores_for_local_identifiers: ignore
    prefer_final_fields: ignore
    prefer_interpolation_to_compose_strings: ignore

linter:
  rules:
    # Enable good practices but disable problematic ones
    avoid_print: false  # Allow print statements for debugging
    use_build_context_synchronously: false  # Allow async context usage
    prefer_typing_uninitialized_variables: false
    strict_top_level_inference: false
    no_leading_underscores_for_local_identifiers: false
    prefer_final_fields: false
    prefer_interpolation_to_compose_strings: false
    
    # Keep important rules
    avoid_empty_else: true
    avoid_relative_lib_imports: true
    avoid_slow_async_io: true
    avoid_types_as_parameter_names: true
    avoid_web_libraries_in_flutter: true
    cancel_subscriptions: true
    close_sinks: true
    control_flow_in_finally: true
    empty_statements: true
    hash_and_equals: true
    invariant_booleans: true
    literal_only_boolean_expressions: true
    no_adjacent_strings_in_list: true
    no_duplicate_case_values: true
    prefer_void_to_null: true
    test_types_in_equals: true
    throw_in_finally: true
    unnecessary_statements: true
    unrelated_type_equality_checks: true
    valid_regexps: true