-- Table to store prizes claimed by users from the fortune wheel.
-- This ensures a user can only spin and claim a prize once.

CREATE TABLE IF NOT EXISTS public.claimed_prizes (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID NOT NULL UNIQUE REFERENCES public.users(id) ON DELETE CASCADE,
  prize_won TEXT NOT NULL,
  claimed_at TIMESTAMPTZ DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Enable Row Level Security
ALTER TABLE public.claimed_prizes ENABLE ROW LEVEL SECURITY;

-- Policies for claimed_prizes
-- Allow users to view their own claimed prize.
CREATE POLICY "Allow users to view their own prize" ON public.claimed_prizes
  FOR SELECT USING (auth.uid() = user_id);

-- Allow users to insert their own prize record.
CREATE POLICY "Allow users to claim a prize" ON public.claimed_prizes
  FOR INSERT WITH CHECK (auth.uid() = user_id);
